name: Famix-Simpl-Diff-CI

on:
  push:
    branches: 
      - main
      - creating_CI
      - differences-list
      - differences-list-with-meta-model

  pull_request:
    branches: 
      - main
      - creating_CI
      - differences-list
      - differences-list-with-meta-model

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Moose64-13 ]
    name: ${{ matrix.smalltalk }}

    steps:
      - uses: actions/checkout@v4
        
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
          
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15

      # JSON
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: exported-json-models
          path: "**/*.json"